config/routes.rb
Rails.application.routes.draw do
  get 'api_credentials/show'
  get 'api_credentials/update'
  devise_for :users

  resources :api_credentials, only: [:index, :update]

  resources :blacklists, only: [:index, :new, :create, :edit, :update]

  get '/blacklisted', to: 'blacklisted#is_blacklisted', as: 'is_blacklisted'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blacklist.rb
class Blacklist < ApplicationRecord

  #### Relationships
  belongs_to :merchant_category
  belongs_to :user, dependent: :destroy

  #### Validations
  validates :user_id,
            :merchant_category_id,
            presence: true

end

app/models/merchant_category.rb
class MerchantCategory < ApplicationRecord
  has_many :blacklists, dependent: :destroy
  has_many :transaction_attempts, dependent: :destroy
end

app/models/transaction_attempt.rb
class TransactionAttempt < ApplicationRecord
  belongs_to :merchant_category
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable,
          :confirmable,
          :registerable,
          :recoverable,
          :rememberable,
          :trackable,
          :validatable

  has_many :blacklists
  has_many :transaction_attempts

end

app/controllers/api_credentials_controller.rb
class ApiCredentialsController < ApplicationController

  before_action :authenticate_user!

  def index
    @api_token = current_user.api_token
  end

  def update
    User.where(id: current_user.id).update_all('api_token = uuid_generate_v4()')
    redirect_to api_credentials_path and return
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

    def after_sign_in_path(resource)
      stored_location_for(resource) || blacklists_path
    end
end

app/controllers/blacklisted_controller.rb
class BlacklistedController < ApplicationController
  before_action :user, :category

  def is_blacklisted
    render error_response(403) and return unless @user.present?
    render json: {authorized: true} and return unless @category.present? && blocked_category?

    record = get_transaction_record
    authorized = !record.new_record?
    record.save

    render json: {authorized: authorized}
  end


  private

    def get_transaction_record
      TransactionAttempt.where(
        created_at: 15.minutes.ago..DateTime.now
      ).find_or_initialize_by(
        transaction_attempt_params
      )
    end

    def blocked_category?
      Blacklist.find_by(user: @user, merchant_category: @category)&.blocked
    end

    def error_response(status)
      {json: {}, status: status}
    end

    def user
      @user = User.find_by(api_token: params[:user_api_token])
    end

    def category
      @category = MerchantCategory.find_by(description: params[:category]&.downcase)
    end

    def transaction_attempt_params
      params.permit(:amount, :merchant_name).merge(user_id: @user.id, merchant_category_id: @category.id)
    end

end

app/controllers/blacklists_controller.rb
class BlacklistsController < ApplicationController

  before_action :authenticate_user!

  def index
    @blacklists = current_user.blacklists.includes(:merchant_category)
  end

  def new
    @blacklist = Blacklist.new
  end

  def edit
    @blacklist = Blacklist.find(params[:id])
  end

  def create
    @blacklist = Blacklist.new(blacklist_params)
    @blacklist.user = current_user
    if @blacklist.save
      redirect_to blacklists_path and return
    end
  end

  def update
    @blacklist = Blacklist.find(params[:id])
    if @blacklist.update(blacklist_params)
      redirect_to blacklists_path and return
    end
  end

  private

    def blacklist_params
      params.require(:blacklist).permit(:id, :blocked, :title, :merchant_name, :merchant_category_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/api_credentials/index.html.slim
.container.mx-auto
  .max-w-5xl.mx-auto.py-6.sm:px-6.lg:px-8
    .mt-3.grid.gap-5.grid-cols-3
      .api-credentials.col-span-1.flex.shadow-md.rounded-md.border-solid.border-2.border-gray-300.h-fit
        .text-container.m-2.w-full
          .title.w-full API Token:
          .text.text-xs.gray-600.my-4.text-center.bg-yellow-100.p-1.rounded-md.border-solid.border-2.border-gray-300 = current_user.api_token
          = link_to api_credential_path(current_user.id), method: :put
            .button.relative.flex.justify-center.py-2.px-4.border.border-transparent.text-sm.font-medium.rounded-md.text-white.bg-indigo-600.hover:bg-indigo-700.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-indigo-500
              | Regenerate
      .api-snippet.col-span-2.flex.shadow-md.rounded-md.border-solid.border-2.border-gray-300
        .text-container.m-2.w-full
          .title.w-full Code Snippet:
          .api-text-block
            pre.bg-gray-700.text-white.mr-4.overflow-x-scroll.rounded-md.p-2
              |
                const beforeTransaction = async (authorization) => {
                  // create the url to call your api with only the merchant name and your user token
                  url = `#{request.protocol}#{request.host}/blacklisted?user_api_token=#{@api_token}&merchant_name=${authorization.merchant.name}&category=${authorization.merchant.category.name}&amount=${authorization.centsAmount}`
                  // call the api with the url
                  const response = await fetch(url, {
                      method: 'GET',
                      headers: {'Content-Type': 'application/json'}
                  });
                  // approve or block the transaction based on the response
                  const json = await response.json();
                  return json.authorized;
                };

app/views/blacklists/_blacklist.html.slim
tr
  td.px-6.py-4.whitespace-nowrap.text-sm.font-medium.text-gray-900
    = blacklist.title
  td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
    = blacklist.merchant_category.description
  td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
    = blacklist.blocked.to_s
  td.px-6.py-4.whitespace-nowrap.text-right.text-sm.font-medium
    = link_to edit_blacklist_path(blacklist)
      text-indigo-600.hover:text-indigo-900
        | Edit

app/views/blacklists/_form.html.slim
- url = blacklist.persisted? ? blacklist_path(method: :patch) : blacklists_path(method: :post)

.h-full.flex.items-center.justify-center.py-12.px-4.sm:px-6.lg:px-8
  .max-w-md.w-full.space-y-8
    div
      h2.mt-6.text-center.text-3xl.font-extrabold.text-gray-900
        | Blocked Merchant Item

    = form_for(blacklist, url: url, class: 'mt-8 space-y-6') do |f|
      / form.mt-8.space-y-6 action="#" method="POST"
      .rounded-md.shadow-sm
        div
          = f.label 'Title', class: 'sr-only', for: 'blacklist_title'
          = f.text_field :title,
                          autofocus: true,
                          class: 'appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm',
                          placeholder: "Title",
                          required: false,
                          type: 'text',
                          value: blacklist.title
        div
          = f.label 'Merchant Category', class: 'sr-only', for: 'blacklist_merchant_category'
          = f.collection_select :merchant_category_id, MerchantCategory.all, :id, :description,
                                {prompt: "Merchant Category"},
                                class: 'block focus:ring-indigo-500 focus:border-indigo-500 w-full shadow-sm sm:text-sm border border-gray-300 rounded-b-md px-3 py-2 text-gray-900',
                                required: true,
                                value: blacklist.merchant_category_id
        div.py-4
          .flex.items-center.justify-between
            .flex.items-center
              = f.check_box :blocked,
                            class: 'h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded',
                            value: blacklist.blocked
              = f.label 'Blocked', class: 'ml-2block text-sm text-gray-900 px-3', for: 'blacklist_blocked'


      div
        button.group.relative.w-full.flex.justify-center.py-2.px-4.border.border-transparent.text-sm.font-medium.rounded-md.text-white.bg-indigo-600.hover:bg-indigo-700.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-indigo-500 type="submit"
          span.absolute.left-0.inset-y-0.flex.items-center.pl-3
            /! Heroicon name: lock-closed
            .h-5.w-5.text-indigo-500.group-hover:text-indigo-400
          | Submit

app/views/blacklists/edit.html.slim
= render 'form', blacklist: @blacklist

app/views/blacklists/index.html.slim
/! This example requires Tailwind CSS v2.0+
.container.mx-auto
  .max-w-5xl.mx-auto.py-6.sm:px-6.lg:px-8
    .flex.flex-col
      .-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
        .py-2.align-middle.inline-block.min-w-full.sm:px-6.lg:px-8
          .shadow.overflow-hidden.border-b.border-gray-200.sm:rounded-lg
            table.min-w-full.divide-y.divide-gray-200
              thead
                tr
                  th.px-6.py-3.bg-gray-50.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope="col"
                    | Title
                  th.px-6.py-3.bg-gray-50.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope="col"
                    | Category
                  th.px-6.py-3.bg-gray-50.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope="col"
                    | Blocked
                  th.px-6.py-3.bg-gray-50.text-right.text-xs.font-medium.text-gray-500.uppercase.tracking-wider scope="col"
                    = link_to new_blacklist_path
                      .button.relative.flex.justify-center.py-2.px-4.border.border-transparent.text-sm.font-medium.rounded-md.text-white.bg-indigo-600.hover:bg-indigo-700.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-indigo-500
                        | New
              tbody.bg-white.divide-y.divide-gray-200
                = render @blacklists

app/views/blacklists/new.html.slim
= render 'form', blacklist: @blacklist

app/views/home/index.html.slim
main
  .max-w-7xl.mx-auto.py-6.sm:px-6.lg:px-8
    .px-4.py-6.sm:px-0.text-center
      |
        Welcome to Snack or Save, a platform intended to supplement your impulse control and improve your spending habits!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snack or Save</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/shared/header' %>

    <%= yield %>
  </body>
</html>